#!/usr/bin/env node
// scripts/build_curated_boards.mjs
//
// Builds the shipped country boards from data/curated-boards.json — hand-checked
// lists where every contender actually belongs to the board they are on.
//
// The bulk export (scripts/build_country_boards.mjs) is kept for reference but
// is not shippable: it filled every board from a country-wide name pool, so 96%
// of its entries were people appearing on more than five boards of their own
// country. Only what this script writes reaches visitors, and it stamps
// verified:true so the site knows the difference.
//
//   node scripts/build_curated_boards.mjs

import fs from 'fs';
import path from 'path';

const SRC = path.resolve('data/curated-boards.json');
const DIR = path.resolve('data/boards');
const SEED = path.resolve('data/country-boards-seed.sql');

const slugify = s => String(s).toLowerCase().normalize('NFD')
  .replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const norm = s => slugify(s).replace(/-/g,' ');

const curated = JSON.parse(fs.readFileSync(SRC,'utf8'));

// --- validate before writing anything ---
const problems = [];
const slugs = new Set();
for (const [code, c] of Object.entries(curated)){
  if (!/^[A-Z]{2}$/.test(code)) problems.push(`${code}: country code must be two letters`);
  for (const b of c.boards){
    const slug = `${code.toLowerCase()}-${slugify(b.name)}`;
    if (slugs.has(slug)) problems.push(`duplicate board slug ${slug}`);
    slugs.add(slug);
    if (!b.contenders.length) problems.push(`${slug}: empty board`);
    const seen = new Set();
    for (const n of b.contenders){
      const k = norm(n);
      if (seen.has(k)) problems.push(`${slug}: duplicate contender "${n}"`);
      seen.add(k);
      if (!n.trim()) problems.push(`${slug}: blank contender`);
      if (/^contender\s*\d*$/i.test(n.trim())) problems.push(`${slug}: placeholder "${n}"`);
    }
  }
}
if (problems.length){ console.error('validation failed:\n  ' + problems.join('\n  ')); process.exit(1); }

// --- write ---
fs.mkdirSync(DIR, { recursive: true });
for (const f of fs.readdirSync(DIR)) fs.unlinkSync(path.join(DIR, f));

const index = [], catRows = [], personRows = [];
const q = s => "'" + String(s).replace(/'/g,"''") + "'";

for (const [code, c] of Object.entries(curated).sort((a,b)=> a[1].country.localeCompare(b[1].country))){
  const boards = c.boards.map((b, i) => {
    const slug = `${code.toLowerCase()}-${slugify(b.name)}`;
    catRows.push(`(${q(slug)},${q(b.name)},${q(c.country)},${q(code)},${q(code + '-' + String(i+1).padStart(2,'0'))})`);
    b.contenders.forEach((n, j) => personRows.push(`(${q(slug)},${j+1},${q(n)},'person')`));
    return {
      id: `${code}-${String(i+1).padStart(2,'0')}`, slug, name: b.name,
      contenders: b.contenders.map((n, j) => ({ rank: j+1, name: n, type: 'person' }))
    };
  });
  fs.writeFileSync(path.join(DIR, `${code}.json`), JSON.stringify({ code, country: c.country, boards }));
  index.push({ code, country: c.country, boards: boards.length,
               contenders: boards.reduce((s,b)=> s + b.contenders.length, 0) });
}

fs.writeFileSync(path.join(DIR,'index.json'), JSON.stringify({
  verified: true,
  source: 'data/curated-boards.json',
  builtAt: new Date().toISOString(),
  countries: index
}, null, 1));

fs.writeFileSync(SEED, `-- data/country-boards-seed.sql (generated by scripts/build_curated_boards.mjs)
-- ${catRows.length} curated boards, ${personRows.length} contenders, ${index.length} countries.
-- Insert-only and re-runnable: existing categories and contenders are untouched.

alter table categories add column if not exists country text;
alter table categories add column if not exists country_code text;
alter table categories add column if not exists board_id text;
create index if not exists categories_country_idx on categories (country_code);

create temp table cb_cat (slug text, name text, country text, country_code text, board_id text) on commit drop;
insert into cb_cat values
${catRows.join(',\n')};

create temp table cb_person (cat_slug text, rank int, name text, kind text) on commit drop;
insert into cb_person values
${personRows.join(',\n')};

insert into categories (slug, name, group_name, country, country_code, board_id, sort_order)
select k.slug, k.name, k.country, k.country, k.country_code, k.board_id, 0
from cb_cat k
where not exists (select 1 from categories c where c.slug = k.slug);

insert into people (slug, category_id, name, wikipedia_url, total_cents)
select p.cat_slug || '-' || lower(regexp_replace(p.name,'[^a-zA-Z0-9]+','-','g')),
       c.id, p.name,
       'https://en.wikipedia.org/wiki/' || replace(p.name,' ','_'),
       0
from cb_person p
join categories c on c.slug = p.cat_slug
where not exists (
  select 1 from people x where x.category_id = c.id and lower(x.name) = lower(p.name)
);
`);

console.log(`countries ${index.length} | boards ${catRows.length} | contenders ${personRows.length}`);
for (const i of index) console.log(`   ${i.code}  ${i.country.padEnd(16)} ${i.boards} boards, ${i.contenders} contenders`);
